process.env.NODE_ENV = 'dev';

var createError = require('http-errors');
var express = require('express');
var path = require('path');
var cookieParser = require('cookie-parser');
var logger = require('morgan');
var cors = require('cors');
var mongoose = require('mongoose');
var passport = require('passport');
var indexRouter = require('./routes/indexRouter');
var usersRouter = require('./routes/usersRouter');
const AppSettings = require(`./config.${process.env.NODE_ENV}`);
var config = new AppSettings();

var app = express();
var swagger = require('./swagger')(app);

app.use(function (req, res, next) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS, PUT, PATCH, DELETE');
  res.setHeader('Access-Control-Allow-Headers', 'X-Requested-With,content-type');
  res.setHeader('Access-Control-Allow-Credentials', true);
  next();
});
app.use(cors());

app.set('view engine', 'jade');

app.use(logger('dev'));

app.use(express.json());
app.use(express.urlencoded({
  extended: false
}));
app.use(cookieParser());
app.use(express.static(path.join(__dirname, 'public')));

app.use(passport.initialize());

app.use('/', indexRouter);
app.use('/users', usersRouter);

// catch 404 and forward to error handler
app.use(function (req, res, next) {
  next(createError(404));
});

// error handler
app.use(function (err, req, res, next) {
  // set locals, only providing error in development
  res.locals.message = err.message;
  let test = req.app.get('env');
  res.locals.error = req.app.get('env') === 'dev' ? err : {};


  mongoose.disconnect();
});

module.exports = app;

// Thanks to Google Copilot.
// Some codes are auto generated by Google Copilot.
